/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthCreateWalletImport } from './routes/auth/create-wallet'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthCreateWalletRoute = AuthCreateWalletImport.update({
  path: '/auth/create-wallet',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/create-wallet': {
      id: '/auth/create-wallet'
      path: '/auth/create-wallet'
      fullPath: '/auth/create-wallet'
      preLoaderRoute: typeof AuthCreateWalletImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/create-wallet': typeof AuthCreateWalletRoute
  '/auth/login': typeof AuthLoginRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/create-wallet': typeof AuthCreateWalletRoute
  '/auth/login': typeof AuthLoginRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/create-wallet': typeof AuthCreateWalletRoute
  '/auth/login': typeof AuthLoginRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/create-wallet' | '/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/create-wallet' | '/auth/login'
  id: '__root__' | '/' | '/auth/create-wallet' | '/auth/login'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCreateWalletRoute: typeof AuthCreateWalletRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCreateWalletRoute: AuthCreateWalletRoute,
  AuthLoginRoute: AuthLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/create-wallet",
        "/auth/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/create-wallet": {
      "filePath": "auth/create-wallet.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
