name: 'Mirror main branch'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  mirror:
    if: github.repository != 'WingRiders/wallet' # Prevent execution in the public repo
    uses: ./.github/workflows/mirror.yml
    with:
      branch: main
    secrets:
      TECHRIDER_SSH_PUBLIC_KEY: ${{ secrets.TECHRIDER_SSH_PUBLIC_KEY }}
      TECHRIDER_SSH_PRIVATE_KEY: ${{ secrets.TECHRIDER_SSH_PRIVATE_KEY }}