name: 'Mirror dev branch'

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  mirror:
    if: github.repository != 'WingRiders/wallet' # Prevent execution in the public repo
    uses: WingRiders/wallet-private/.github/workflows/mirror.yml@main
    with:
      branch: dev
