name: Test

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['*']

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.27

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run check

      - name: Run build
        run: bun run build

      - name: Run test
        run: bun run test
